package frc.robot.commands;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.Set;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathPlannerAuto;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Robot;
import frc.robot.Constants.SubsystemConstants.Vision;
import frc.robot.Constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.utility.LimelightHelpers;
import frc.robot.subsystems.utility.LimelightHelpers.PoseEstimate;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * 
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SwerveRequest.ApplyChassisSpeeds */
        SwerveRequest.ApplyRobotSpeeds m_applyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    // private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         /* This is in radians per second², but SysId only supports "volts per second" */
    //         Volts.of(Math.PI / 6).per(Second),
    //         /* This is in radians per second, but SysId only supports "volts" */
    //         Volts.of(Math.PI),
    //         null, // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         output -> {
    //             /* output is actually radians per second,    but SysId only supports "volts" */
    //             setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
    //             /* also log the requested output for SysId */
    //             SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
    //         },
    //         null,
    //         this
    //     )
    // );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }
    /**
     * Configures the PathPlanner AutoBuilder for this drivetrain. This allows you to use PathPlanner's path following features with this drivetrain.
     */

    private void configurePathPlanner(){
        RobotConfig config = null;
            try{
                config = RobotConfig.fromGUISettings();
            } catch (Exception e) {
                // Loud failure: without this config AutoBuilder is never configured and ALL
                // path following silently dies. Surface it on the Driver Station.
                DriverStation.reportError(
                    "PathPlanner RobotConfig failed to load -- autos and path following are DISABLED: "
                        + e.getMessage(), e.getStackTrace());
            }
        if(config != null){
                  //Configure Auto Builder
            AutoBuilder.configure(
            () -> this.getState().Pose, // Robot pose supplier
            pose -> this.resetPose(pose), // Reset odometry to the path's full start pose (X, Y AND rotation -- seedFieldCentric only set heading and silently dropped X/Y)
            () -> this.getState().Speeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
            (speeds, feedforwards) -> this.setControl(m_applyRobotSpeeds.withSpeeds(speeds).withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesX()).withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesY())), // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
            new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                    new PIDConstants(5.0, 0.0, 0.0), // Translation PID (m/s per m of error; old 0.0001 was effectively open-loop). TODO tune on robot
                    new PIDConstants(5, 0.0, 0.0) // Rotation PID constants
            ),
            config, // The robot configuration
            () -> {

              // Boolean supplier that controls when the path will be mirrored for the red alliance
              // This will flip the path being followed to the red side of the field.
              // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

              var alliance = DriverStation.getAlliance();
              if (alliance.isPresent()) {
                return alliance.get() == DriverStation.Alliance.Red;
              }
              return false;
            },
            this // Reference to this subsystem to set requirements
            );
        }
    }
    
    /**
     * 
     * Returns a command that runs the specified path from PathPlanner. The path must be located in the "paths" folder in the project directory, and should be created using the PathPlanner tool.
     * @param name
     * @return Auto Command
     */
        public Command getAuton(String name){
            return new PathPlannerAuto(name);
        }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
        // Vision pose correction (MegaTag2). Disabled by default until the Limelight's mounting,
        // pipeline, and field map are verified on the robot -- flip Vision.ENABLE_MEGATAG2_POSE.
        if (Vision.ENABLE_MEGATAG2_POSE) {
            updateVisionPose();
        }
    }

    /**
     * Fuses a Limelight MegaTag2 pose estimate into the drivetrain's pose estimator.
     * Always uses the BLUE-origin estimate: PathPlanner (and this drivetrain's pose) keep the
     * origin on the blue side for both alliances, so alliance-switching to the red-origin
     * estimate would corrupt the pose. Safe to call with no Limelight connected.
     */
    private void updateVisionPose() {
        // Feed the Limelight our gyro yaw (deg, blue-origin) -- required for MegaTag2.
        LimelightHelpers.SetRobotOrientation(Vision.CAM_LIMELIGHT,
            this.getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
        LimelightHelpers.SetIMUMode(Vision.CAM_LIMELIGHT,
            (DriverStation.isAutonomous()) ? 1 : 4
        );
            // 1 -> EXTERNAL_SEED : Seed internal IMU
            // 4 -> INTERNAL_EXTERNAL_ASSIST : Use internal IMU + MT1

        PoseEstimate mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(Vision.CAM_LIMELIGHT);
        if (mt2 == null || mt2.tagCount == 0) {
            return; // no Limelight data / no tags in view
        }
        if (Math.abs(this.getPigeon2().getAngularVelocityZDevice().getValueAsDouble()) > 360) {
            return; // spinning too fast for a trustworthy MegaTag2 solve
        }
        // Trust MegaTag2 X/Y, never its yaw (huge theta std dev) -- the Pigeon owns heading.
        this.addVisionMeasurement(mt2.pose, mt2.timestampSeconds, VecBuilder.fill(0.7, 0.7, 9999999));
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Command rotateToAngle(double targetAngleDegrees){
        return rotateToAngle(() -> targetAngleDegrees);
    }

    /**
     * Supplier overload so the target can be a LIVE value (e.g. a vision bearing that updates
     * every loop). A plain double is frozen at binding-construction time -- binding
     * rotateToAngle(shooter.getDegreesToAlignToTarget()) would rotate to whatever the value was
     * at boot (0 deg) forever; bind rotateToAngle(shooter::getDegreesToAlignToTarget) instead.
     */
    public Command rotateToAngle(DoubleSupplier targetAngleDegrees){
        var request = new SwerveRequest.FieldCentricFacingAngle();
        // The HeadingController gains default to 0 -- without this the request outputs zero
        // rotation and the command would hold the drivetrain forever. Radians in, rad/s out.
        request.HeadingController.setPID(5.0, 0.0, 0.0); // TODO tune on robot
        request.HeadingController.enableContinuousInput(-Math.PI, Math.PI); // take the short way around
        // Cap the commanded spin (P-only at 5 rad/s per rad could otherwise demand ~15 rad/s).
        request.MaxAbsRotationalRate = 1.5 * Math.PI; // rad/s. TODO tune on robot

        // The command must END when on target (or on the timeout backstop) so the drivetrain
        // returns to the driver's default drive command -- chaining an Idle request here would
        // hold the drivetrain forever and lock the driver out.
        return this.applyRequest(() ->
            request.withTargetDirection(
                Rotation2d.fromDegrees(targetAngleDegrees.getAsDouble())
            )
        ).until(() ->
            // Rotation2d.minus wraps, so 179 deg vs -179 deg reads as 2 deg apart, not 358.
            Math.abs(
                this.getState().Pose.getRotation()
                    .minus(Rotation2d.fromDegrees(targetAngleDegrees.getAsDouble())).getDegrees()
            ) < 2 // deg. P-only control may hold a small steady-state error; 1 deg could never latch
        ).withTimeout(2.0); // s -- backstop so a stalled align can never hang the drivetrain. TODO tune
    }

    public Command driveToPose(Pose2d targetPose){
        PathConstraints constraints = new PathConstraints(
            Vision.PP_MAX_VELOCITY, 
            Vision.PP_MAX_ACCELERATION, 
            Vision.PP_MAX_ANGULAR_VELOCITY, 
            Vision.PP_MAX_ANGULAR_ACCELERATION
        );
        Command pathfindingCommand = AutoBuilder.pathfindToPose(targetPose, constraints, 0.0);
        return pathfindingCommand;
    }

    public Command driveToPose(Translation2d targetTranslation, Translation2d velocityTranslation){
        // Deferred so the CURRENT pose is read when the command is scheduled, not when the
        // binding is constructed at boot.
        return Commands.defer(() -> {
            double velocityMag = velocityTranslation.getNorm();
            if(velocityMag < 0.001){
                return Commands.none();
            }

            // Distance from where the robot IS to the target. The old code used
            // targetTranslation.getNorm() -- the target's distance from the FIELD ORIGIN (0,0),
            // which is unrelated to how far the robot actually has to travel.
            double distance = targetTranslation.minus(this.getState().Pose.getTranslation()).getNorm();
            double time = distance / velocityMag;

            var idle = new SwerveRequest.Idle();

            return this.applyRequest(() ->
                m_applyRobotSpeeds.withSpeeds(
                    ChassisSpeeds.fromFieldRelativeSpeeds(
                        velocityTranslation.getX(),
                        velocityTranslation.getY(),
                        0,
                        this.getState().Pose.getRotation()
                    )
                )
            ).withTimeout(time)
            // One-shot stop so the command ENDS and the driver's default command resumes -- a
            // run-forever applyRequest(Idle) leg would hold the drivetrain and lock the driver out.
            .andThen(this.runOnce(() -> this.setControl(idle)));
        }, Set.of(this));
    }
}
